---
version: '3'
services:

## DB and Cache
  redispf:
    image: redis:5-buster
    restart: unless-stopped
    volumes:
      - "./redis-data:/data"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  dbpf:
    restart: unless-stopped
    image: postgres:12
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pixelfed
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks:
  internal:
    internal: true
  external:
    driver: bridge






