---
version: '3'
services:

## DB and Cache
  redis:
    image: redis:5-buster
    restart: unless-stopped
    volumes:
      - "./redis-data:/data"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  postgres:
    restart: unless-stopped
    image: postgres:12
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pixelfed
      - POSTGRES_USER=pixelfeduser
      - POSTGRES_PASSWORD=pixelfedpass

## App and Worker
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    image: pixelfed
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - "./.env.docker:/var/www/.env"
    networks:
      - external
      - internal
    ports:
        - "9000:9000"
    command: php-fpm

  worker:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    image: pixelfed
    restart: unless-stopped
    env_file:
      - .env.docker
    networks:
      - external  # Required for ActivityPub
      - internal
    command: gosu www-data php artisan horizon

networks:
  internal:
    internal: true
  external:
    driver: bridge






